#Puerto del servidor
server:
  port: 8081
#Nombre del microservicio
spring:
  application:
    name: clima-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


